app_de_cero/config/routes.rb
Rails.application.routes.draw do
  devise_for :local_users
  devise_for :match_users
  root 'static_pages#home'
  get '/login' ,to: 'static_pages#login'
  get '/match_home' ,to: 'match_app#match_home'
  get '/match_perfil' ,to: 'match_app#match_perfil'
  get '/match_match' ,to: 'match_app#match_match'
  get '/match_locales' ,to: 'match_app#match_locales'
  get '/match_inbox' ,to: 'match_app#match_inbox'
  get '/local_home' ,to: 'local_app#local_home'
  get '/local_locales' ,to: 'local_app#local_locales'
  get '/local_mi_local' ,to: 'local_app#local_mi_local'
  get '/local_muro' ,to: 'local_app#local_muro'
end

app_de_cero/app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app_de_cero/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse <%=@style%>">
  <div class="container">
      <% if @logo  %>
        <%= link_to @logo[:name], @logo[:link],id: "logo" %>
      <%else%>
        <%= link_to "Grupo43App", root_path ,id: "logo" %>
      <%end%>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if @nav_elements  %>
            <% for elem in @nav_elements  %>
              <li> <%=link_to elem[:name],   elem[:link], method: elem[:method] %></li>
            <%end%>
          <%end%>
        </ul>
      </nav>
    </div>
</header>

app_de_cero/app/views/layouts/_login_user_local.html.erb
<% if signed_in? %>
  <%= link_to "Salir ", destroy_local_user_session_path, method: :delete, :class => "center"%>
<% else %>
  <%= link_to "Registrarse a Local", new_local_user_registration_path, :class => "center"%><br>
  <%= link_to "Ingresar a Local", new_local_user_session_path, :class => "center"%>
<% end %>

app_de_cero/app/views/layouts/_login_user_match.html.erb
<% if signed_in? %>
  <%= link_to "Salir", destroy_match_user_session_path, method: :delete, :class => "btn btn-inverse" %>
<% else %>
  <%= link_to "Registrarse a Match", new_match_user_registration_path, :class => "center"%><br>
  <%= link_to "Ingresar a Match", new_match_user_session_path, :class => "center"%>
<% end %>

app_de_cero/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%=@style%>body">
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>